name: 'Rust Release Action'
description: 'Automate Rust project releases with changelog extraction, version validation, and cross-platform builds'
author: 'Michael Klishin'

branding:
  icon: 'package'
  color: 'orange'

inputs:
  command:
    description: 'Command: extract-changelog, validate-version, get-version, release-linux, release-macos, release-windows, release-windows-msi'
    required: true

  version:
    description: 'Version to extract (without v prefix)'
    required: false

  changelog:
    description: 'Path to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'

  output:
    description: 'Output file for release notes'
    required: false
    default: 'release_notes.md'

  tag:
    description: 'Git tag (defaults to GITHUB_REF_NAME)'
    required: false

  expected-version:
    description: 'Expected version (defaults to NEXT_RELEASE_VERSION variable)'
    required: false

  manifest:
    description: 'Path to Cargo.toml'
    required: false
    default: 'Cargo.toml'

  target:
    description: 'Rust target triple'
    required: false

  binary-name:
    description: 'Binary name (defaults to package name)'
    required: false

  package:
    description: 'Cargo package name for workspace builds'
    required: false

  no-default-features:
    description: 'Build with --no-default-features'
    required: false
    default: 'false'

  target-rustflags:
    description: 'Extra RUSTFLAGS for the build'
    required: false

  archive:
    description: 'Create archive (.tar.gz on Linux/macOS, .zip on Windows)'
    required: false
    default: 'false'

  working-directory:
    description: 'Working directory for commands'
    required: false
    default: '.'

outputs:
  version:
    description: 'Extracted or validated version'
    value: ${{ steps.run.outputs.version }}

  release_notes_file:
    description: 'Path to release notes file'
    value: ${{ steps.run.outputs.release_notes_file }}

  artifact:
    description: 'Artifact filename'
    value: ${{ steps.run.outputs.artifact }}

  artifact_path:
    description: 'Full path to artifact'
    value: ${{ steps.run.outputs.artifact_path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Nu shell
      uses: hustcer/setup-nu@56361e0eb7e0e93e97d4925f1ed07d767615f0b1 # v3.17
      with:
        version: '0.110.0'

    - name: Run command
      id: run
      shell: nu {0}
      working-directory: ${{ inputs.working-directory }}
      run: |
        let scripts = $"($env.GITHUB_ACTION_PATH)/scripts"
        $env.NU_LIB_DIRS = [$scripts]

        match $"${{ inputs.command }}" {
            "extract-changelog" => {
                $env.VERSION = $"${{ inputs.version }}"
                $env.CHANGELOG_PATH = $"${{ inputs.changelog }}"
                $env.OUTPUT_PATH = $"${{ inputs.output }}"
                nu $"($scripts)/extract-changelog.nu"
            }
            "validate-version" => {
                $env.TAG = if "${{ inputs.tag }}" != "" { "${{ inputs.tag }}" } else { $env.GITHUB_REF_NAME? | default "" }
                $env.EXPECTED_VERSION = if "${{ inputs.expected-version }}" != "" { "${{ inputs.expected-version }}" } else { $env.NEXT_RELEASE_VERSION? | default "" }
                nu $"($scripts)/validate-version.nu"
            }
            "get-version" => {
                $env.MANIFEST_PATH = $"${{ inputs.manifest }}"
                nu $"($scripts)/get-version.nu"
            }
            "release-linux" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                nu $"($scripts)/release-linux.nu"
            }
            "release-macos" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                nu $"($scripts)/release-macos.nu"
            }
            "release-windows" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                if "${{ inputs.archive }}" == "true" { $env.ARCHIVE = "true" }
                nu $"($scripts)/release-windows.nu"
            }
            "release-windows-msi" => {
                if "${{ inputs.target }}" != "" { $env.TARGET = "${{ inputs.target }}" }
                if "${{ inputs.binary-name }}" != "" { $env.BINARY_NAME = "${{ inputs.binary-name }}" }
                if "${{ inputs.package }}" != "" { $env.PACKAGE = "${{ inputs.package }}" }
                if "${{ inputs.no-default-features }}" == "true" { $env.NO_DEFAULT_FEATURES = "true" }
                if "${{ inputs.target-rustflags }}" != "" { $env.TARGET_RUSTFLAGS = "${{ inputs.target-rustflags }}" }
                nu $"($scripts)/release-windows-msi.nu"
            }
            _ => {
                print $"(ansi red)ERROR:(ansi reset) unknown command '${{ inputs.command }}'"
                exit 1
            }
        }
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        NEXT_RELEASE_VERSION: ${{ vars.NEXT_RELEASE_VERSION }}
