# Native installers: macOS .dmg and Windows .msi
name: Installers

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      version: ${{ steps.validate.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: michaelklishin/rust-release-action@v0
        id: validate
        with:
          command: validate-version

  macos-dmg:
    needs: validate
    runs-on: macos-14
    timeout-minutes: 30
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal

      - uses: michaelklishin/rust-release-action@v0
        id: build
        with:
          command: release-macos-dmg
          target: ${{ matrix.target }}
          locked: 'true'

      - uses: actions/upload-artifact@v4
        with:
          name: dmg-${{ matrix.target }}
          path: ${{ steps.build.outputs.artifact_path }}

  windows-msi:
    needs: validate
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal

      # Requires wix/main.wxs, use `cargo wix init` to generate
      - uses: michaelklishin/rust-release-action@v0
        id: build
        with:
          command: release-windows-msi
          target: x86_64-pc-windows-msvc
          locked: 'true'

      - uses: actions/upload-artifact@v4
        with:
          name: msi-x86_64
          path: ${{ steps.build.outputs.artifact_path }}

  release:
    needs: [validate, macos-dmg, windows-msi]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: michaelklishin/rust-release-action@v0
        with:
          command: extract-changelog
          version: ${{ needs.validate.outputs.version }}

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Collect installers
        run: |
          mkdir -p release
          find artifacts -type f \( -name "*.dmg" -o -name "*.msi" \) -exec cp {} release/ \;

      - uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.md
          files: release/*
