# Generate package manager manifests after a release is published
name: Package Managers

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  homebrew:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Download release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p assets
          gh release download ${{ env.VERSION }} --pattern "*.tar.gz" --pattern "*.sha256" --dir assets

      - name: Get checksums
        id: checksums
        run: |
          echo "macos_arm64=$(cat assets/*aarch64-apple-darwin*.sha256 | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "macos_x64=$(cat assets/*x86_64-apple-darwin*.sha256 | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "linux_x64=$(cat assets/*x86_64-unknown-linux-gnu*.sha256 | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - uses: michaelklishin/rust-release-action@v0
        with:
          command: generate-homebrew
          version: ${{ env.VERSION }}
          pkg-description: 'A command-line tool'
          pkg-homepage: ${{ github.event.repository.html_url }}
          pkg-license: 'MIT'
          brew-macos-arm64-url: ${{ github.event.release.html_url }}/download/${{ env.VERSION }}/myapp-${{ env.VERSION }}-aarch64-apple-darwin.tar.gz
          brew-macos-arm64-sha256: ${{ steps.checksums.outputs.macos_arm64 }}
          brew-macos-x64-url: ${{ github.event.release.html_url }}/download/${{ env.VERSION }}/myapp-${{ env.VERSION }}-x86_64-apple-darwin.tar.gz
          brew-macos-x64-sha256: ${{ steps.checksums.outputs.macos_x64 }}
          brew-linux-x64-url: ${{ github.event.release.html_url }}/download/${{ env.VERSION }}/myapp-${{ env.VERSION }}-x86_64-unknown-linux-gnu.tar.gz
          brew-linux-x64-sha256: ${{ steps.checksums.outputs.linux_x64 }}

      - uses: actions/upload-artifact@v4
        with:
          name: homebrew-formula
          path: target/homebrew/

  aur:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Get source checksum
        id: source
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          URL="https://github.com/${{ github.repository }}/archive/refs/tags/${{ env.VERSION }}.tar.gz"
          SHA256=$(curl -sL "$URL" | sha256sum | cut -d' ' -f1)
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - uses: michaelklishin/rust-release-action@v0
        with:
          command: generate-aur
          version: ${{ env.VERSION }}
          aur-maintainer: 'Your Name <you@example.com>'
          aur-source-url: ${{ steps.source.outputs.url }}
          aur-source-sha256: ${{ steps.source.outputs.sha256 }}
          pkg-description: 'A command-line tool'
          pkg-homepage: ${{ github.event.repository.html_url }}
          pkg-license: 'MIT'

      - uses: actions/upload-artifact@v4
        with:
          name: aur-pkgbuild
          path: target/aur/

  winget:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p assets
          gh release download ${{ env.VERSION }} --pattern "*windows*.zip" --pattern "*windows*.sha256" --dir assets

      - name: Get checksum
        id: checksums
        run: |
          echo "x64=$(cat assets/*x86_64-pc-windows*.sha256 | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - uses: michaelklishin/rust-release-action@v0
        with:
          command: generate-winget
          version: ${{ env.VERSION }}
          winget-publisher: 'Your Name'
          winget-license-url: ${{ github.event.repository.html_url }}/blob/main/LICENSE
          winget-x64-url: ${{ github.event.release.html_url }}/download/${{ env.VERSION }}/myapp-${{ env.VERSION }}-x86_64-pc-windows-msvc.zip
          winget-x64-sha256: ${{ steps.checksums.outputs.x64 }}
          pkg-description: 'A command-line tool'
          pkg-homepage: ${{ github.event.repository.html_url }}
          pkg-license: 'MIT'

      - uses: actions/upload-artifact@v4
        with:
          name: winget-manifest
          path: target/winget/
